name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: # Define the environment for the deployment job
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --base-href /${{ github.event.repository.name }}/  # Crucial for correct resource paths

      - name: Setup Pages
        uses: actions/configure-pages@v4  # Adds a configuration step

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Updated to v3
        with:
          path: build/web/

      - name: Deploy to GitHub Pages
        id: deployment  # Adds an ID to reference the output URL
        uses: actions/deploy-pages@v4  # Updated to v4